server:
  port: 8989

spring:
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
    gateway:
      routes:
        - id: user_route
          #uri: http://localhost:9999/
          uri: lb://users
          predicates:
            - Path=/feign/**

        - id: product_route
          #uri: http://localhost:9998/
          uri: lb://products
          predicates:
            - Path=/product/**

      discovery:
        locator:
          enabled: true #\u5F00\u542F\u6839\u636E\u670D\u52A1\u540D\u52A8\u6001\u83B7\u53D6\u8DEF\u7531\u5730\u5740

management:
  endpoints:
    web:
      exposure:
        include: "*" # \u66B4\u9732\u8DEF\u7531\u89C4\u5219web\u7AEF\u70B9 /actuator/gateway/routes
